name: amber_signer
description: Amber signer for models
version: 0.2.0

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  signer_plugin:
    git:
      url: https://github.com/chebizarro/flutter-signer-plugin
      ref: baa5b2
  models: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  models:
    # path: ../models
    git:
      url: https://github.com/purplebase/models
      ref: ca70b39728acf0de44354615d3b161b4a36a209c
